<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Gigabyte.Cashback</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Gigabyte.Cashback.EntityFrameworkCore\Gigabyte.Cashback.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\Gigabyte.Cashback.Application.Tests\Gigabyte.Cashback.Application.Tests.csproj" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" Version="10.6.0" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.13" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

</Project>
